#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Prepare the local dev environment.
# Invoke from the root of the git repo as "ci/bootstrap".
################################################################################

trap finish EXIT

main() {
  setup_python_path
  install_precommit
}

finish() {
  declare -ri RC=$?

  if [[ $RC -eq 0 ]]; then
    echo "$0 OK"
  else
    echo "[ERROR] $0 failed with exit status $RC"
  fi
}

setup_python_path() {
  PYTHON_PATH="$(python -c "import site; print(site.USER_BASE)")"
  readonly PYTHON_PATH

  if ! grep "${PYTHON_PATH}/bin" <(printenv PATH) &> /dev/null; then
    export PATH="${PATH}:${PYTHON_PATH}/bin"
  fi
}

install_precommit() {
  if ! command -v pre-commit &> /dev/null; then
    pip install --user -Iv --compile --no-cache-dir pre-commit
  fi
}

run_precommit() {
  pre-commit run --all-files --verbose
}

main
