#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Build the image(s). Invoke as "ci/build".
################################################################################

. ci/functions.sh

cat >ci/vars <<EOF
declare -rx  VERSION=1.4.0
declare -rx  BUILD_DATE=$(date +%Y%m%dT%H%M)
declare -rx  VCS_REF=$(git describe --abbrev=7 --tags --always)
declare -rx  TAG=\${VERSION}-\${BUILD_DATE}-git-\${VCS_REF}
EOF

. ci/vars

info Build the runtime image.
run docker-compose build scanner

info Build an image we use in the test harness.
run docker-compose build sleeper

info Show image sizes.
run docker images | grep ssllabs-scan
