#!/bin/sh
set -e

cat > ci/vars <<EOF
  VERSION=1.4.0
  BUILD_DATE=$(date +%Y%m%dT%H%M)
  VCS_REF=${CIRCLE_SHA1:0:7}
  TAG=\${VERSION}-\${BUILD_DATE}-git-\${VCS_REF}

  export VERSION
  export BUILD_DATE
  export VCS_REF
  export TAG
EOF

. ci/vars

ci/clean

# Build the builder.
docker-compose build builder

# Copy binary into local directory.
docker create --name scanbuild builder true
docker cp scanbuild:/tmp/ssllabs-scan-${VERSION}/ssllabs-scan .
docker cp scanbuild:/tmp/sleeper .

# Copy certs into local directory.
docker cp scanbuild:/etc/ssl/certs/ca-certificates.crt .

# Build the runtime image.
docker-compose build scanner

# Build an image we use in the test harness.
docker-compose build sleeper

# Show image sizes.
docker images | grep ssllabs-scan
