#!/bin/bash
set -e
set -u
set -o pipefail

################################################################################
# Clean the local dev environment.
################################################################################

. ci/functions.sh

echo
echo Clean up from previous runs.
rm -f ssllabs-scan || :
docker rm -f scanbuild || :
docker rmi -f scanbuild || :
