#!/bin/bash
set -eEu
set -o pipefail

################################################################################
# Clean the local dev environment.
################################################################################

. ci/functions.sh

info Clean up from previous runs.
run rm -f ssllabs-scan || :
run docker rm -f scanbuild || :
run docker rmi -f scanbuild || :
