#!/bin/bash
set -e
set -u
set -o pipefail

################################################################################
# Publish the image(s) to docker hub.
################################################################################

. ci/functions.sh

. ci/vars

echo
echo Publish images.
# shellcheck disable=SC2154
docker login -u "${user}" -p "${pass}"
docker tag jumanjiman/ssllabs-scan jumanjiman/ssllabs-scan:"${TAG}"
docker push jumanjiman/ssllabs-scan:"${TAG}"
docker push jumanjiman/ssllabs-scan:latest
docker logout

echo
echo Trigger update on microbadger.
curl -X POST 'https://hooks.microbadger.com/images/jumanjiman/ssllabs-scan/dsQe3-XA4hIfa2qdd_qndJZrOMg='
