#!/bin/sh
set -e

. ci/vars
docker login -u ${user} -p ${pass}
docker tag jumanjiman/ssllabs-scan jumanjiman/ssllabs-scan:${TAG}
docker push jumanjiman/ssllabs-scan:${TAG}
docker push jumanjiman/ssllabs-scan:latest
docker logout
curl -X POST 'https://hooks.microbadger.com/images/jumanjiman/ssllabs-scan/dsQe3-XA4hIfa2qdd_qndJZrOMg='
